Resources:
  ProcessingTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: ${self:service}-${self:provider.stage}-topic

Outputs:
  ProcessingTopicArn:
    Value: !Ref ProcessingTopic
    Export:
      Name: ${self:service}-${self:provider.stage}-TopicArn
